using System.Collections.Immutable;
using System.Text;
using HotChocolate.Types.Analyzers.Models;
using Microsoft.CodeAnalysis;

namespace HotChocolate.Types.Analyzers.Generators;

public sealed class CommandServiceGenerator : ISyntaxGenerator
{
    public void Generate(
        SourceProductionContext context,
        string assemblyName,
        ImmutableArray<SyntaxInfo> syntaxInfos,
        Action<string, string> addSource)
    {
        var commandServices = syntaxInfos
            .OfType<CommandServiceInfo>()
            .Where(cs => cs.Diagnostics.Length == 0)
            .ToList();

        if (commandServices.Count == 0)
        {
            return;
        }

        // Group by namespace
        var servicesByNamespace = commandServices
            .GroupBy(cs => cs.Namespace)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var item in servicesByNamespace)
        {
            var namespaceName = item.Key;
            var servicesInNamespace = item.Value;

            var sourceBuilder = new StringBuilder();

            WriteHeader(sourceBuilder, namespaceName);

            foreach (var commandService in servicesInNamespace.OrderBy(cs => cs.ServiceName))
            {
                GenerateHandlersForService(sourceBuilder, commandService);
            }

            if (sourceBuilder.Length > 0)
            {
                var fileName = $"{SanitizeFileName(namespaceName)}.CommandHandlers.g.cs";
                addSource(fileName, sourceBuilder.ToString());
            }
        }
    }

    private static void WriteHeader(StringBuilder builder, string namespaceName)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using MediatR;");
        builder.AppendLine("using CSharpFunctionalExtensions;");
        builder.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName};");
            builder.AppendLine();
        }
    }

    private static void GenerateHandlersForService(
        StringBuilder builder,
        CommandServiceInfo commandService)
    {
        var serviceName = commandService.ServiceName;
        var serviceTypeName = commandService.ServiceFullName;

        foreach (var method in commandService.Methods)
        {
            var commandType = method.CommandType;
            var commandTypeName = commandType.ToDisplayString();
            var commandSimpleName = commandType.Name;

            var handlerName = commandService.GetHandlerName(commandSimpleName);

            // Determine result type
            string resultType;
            if (method.HasGenericResult && method.ResultTypeName != null)
            {
                resultType = $"CSharpFunctionalExtensions.Result<{method.ResultTypeName}>";
            }
            else
            {
                resultType = "CSharpFunctionalExtensions.Result";
            }

            // Get services (excluding duplicates)
            var services = GetUniqueServices(commandService, method);

            // Generate handler class with primary constructor
            GenerateHandlerClass(
                builder,
                handlerName,
                commandTypeName,
                resultType,
                serviceName,
                serviceTypeName,
                method.MethodName,
                services,
                commandService.IsPublic);

            builder.AppendLine();
        }
    }

    private static ImmutableArray<ServiceParameterInfo> GetUniqueServices(
        CommandServiceInfo commandService,
        CommandMethodInfo method)
    {
        var allServices = new Dictionary<string, ServiceParameterInfo>();

        // Add the main service
        var mainService = new ServiceParameterInfo(
            GetParameterName(commandService.ServiceName),
            commandService.ServiceType,
            ServiceParameterKind.Service);
        allServices[mainService.TypeName] = mainService;

        // Add method parameters (excluding command and cancellation token)
        foreach (var param in method.Parameters)
        {
            var paramTypeName = param.Type.ToDisplayString();

            // Skip if we already have this type
            if (allServices.ContainsKey(paramTypeName))
            {
                continue;
            }

            var serviceKind = DetermineServiceKind(param.Type);
            var paramName = GetParameterName(param.Type.Name);

            var serviceParam = new ServiceParameterInfo(
                paramName,
                param.Type,
                serviceKind);

            allServices[paramTypeName] = serviceParam;
        }

        return allServices.Values.ToImmutableArray();
    }

    private static ServiceParameterKind DetermineServiceKind(ITypeSymbol type)
    {
        var typeName = type.ToDisplayString();

        if (typeName.Contains("ILogger") || typeName.Contains("Microsoft.Extensions.Logging"))
        {
            return ServiceParameterKind.Logger;
        }

        if (typeName.Contains("HttpContext") || typeName.Contains("Microsoft.AspNetCore.Http"))
        {
            return ServiceParameterKind.HttpContext;
        }

        if (typeName.Contains("IMediator") || typeName.Contains("ISender") || typeName.Contains("MediatR"))
        {
            return ServiceParameterKind.Mediator;
        }

        return ServiceParameterKind.Service;
    }

    private static void GenerateHandlerClass(
        StringBuilder builder,
        string handlerName,
        string commandTypeName,
        string resultType,
        string serviceName,
        string serviceTypeName,
        string methodName,
        ImmutableArray<ServiceParameterInfo> services,
        bool isPublic)
    {
        var accessibility = isPublic ? "public" : "internal";

        // Build constructor parameters without duplicates
        var parameters = new List<string>();
        var seenTypes = new HashSet<string>();

        foreach (var service in services)
        {
            if (seenTypes.Add(service.TypeName))
            {
                var paramName = service.ParameterName;
                parameters.Add($"{service.TypeName} {paramName}");
            }
        }

        // Class declaration with primary constructor
        builder.Append($"{accessibility} class {handlerName}(");
        builder.Append(string.Join(", ", parameters));
        builder.Append($") : IRequestHandler<{commandTypeName}, {resultType}>");
        builder.AppendLine();
        builder.AppendLine("{");

        // Handle method - NO private fields, use primary constructor parameters directly
        builder.AppendLine($"    public async Task<{resultType}> Handle(");
        builder.AppendLine($"        {commandTypeName} request,");
        builder.AppendLine("        CancellationToken cancellationToken)");
        builder.AppendLine("    {");

        // Build the method call using primary constructor parameters
        // Find the service parameter name
        var serviceParamName = services
            .FirstOrDefault(s => s.TypeName == serviceTypeName)
            ?.ParameterName ?? GetParameterName(serviceName);

        builder.AppendLine($"        return await {serviceParamName}.{methodName}(");
        builder.AppendLine("            request,");

        // Add other parameters from services (excluding the main service and cancellation token)
        var otherServices = services
            .Where(s => s.TypeName != serviceTypeName && s.Kind != ServiceParameterKind.CancellationToken)
            .ToList();

        //var methodParams = new List<string>();
        ////foreach (var service in otherServices)
        ////{
        ////    methodParams.Add(service.ParameterName);
        ////}

        //if (methodParams.Count > 0)
        //{
        //    builder.AppendLine($"            {string.Join(", ", methodParams)},");
        //}

        builder.AppendLine("            cancellationToken);");

        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static string GetParameterName(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "service";
        }

        // Remove 'I' prefix for interfaces
        if (name.StartsWith("I") && name.Length > 1 && char.IsUpper(name[1]))
        {
            name = name.Substring(1);
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string SanitizeFileName(string namespaceName)
    {
        if (string.IsNullOrEmpty(namespaceName))
        {
            return "Global";
        }

        return namespaceName
            .Replace('.', '_')
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(' ', '_');
    }
}
