using System.Text;
using HotChocolate.Types.Analyzers.Helpers;

namespace HotChocolate.Types.Analyzers.FileBuilders;

public sealed class CommandServiceFileBuilder : IDisposable
{
    private StringBuilder _sb;
    private CodeWriter _writer;
    private bool _disposed;

    public CommandServiceFileBuilder()
    {
        _sb = PooledObjects.GetStringBuilder();
        _writer = new CodeWriter(_sb);
    }

    public void WriteHeader()
    {
        _writer.WriteIndentedLine("// <auto-generated/>");
        _writer.WriteLine();
        _writer.WriteIndentedLine("#nullable enable");
        _writer.WriteIndentedLine("#pragma warning disable");
        _writer.WriteLine();
        //_writer.WriteIndentedLine("using System;");
        //_writer.WriteIndentedLine("using System.Threading;");
        //_writer.WriteIndentedLine("using System.Threading.Tasks;");
        //_writer.WriteIndentedLine("using MediatR;");
        //_writer.WriteIndentedLine("using CSharpFunctionalExtensions;");
        _writer.WriteLine();
    }
    public void WriteUsings(params string[] usings)
    {
        foreach (var u in usings)
        {
            _writer.WriteIndentedLine("using {0};", u);
        }
        _writer.WriteLine();
    }
    public void WriteUsing(string u)
    {
        _writer.WriteIndentedLine("using {0};", u);
    }

    public void WriteBeginNamespace(string ns)
    {
        _writer.WriteIndentedLine("namespace {0}", ns);
        _writer.WriteIndentedLine("{");
        _writer.IncreaseIndent();
    }

    public void WriteEndNamespace()
    {
        _writer.DecreaseIndent();
        _writer.WriteIndentedLine("}");
        _writer.WriteLine();
    }

    public void WriteHandlerClass(
        string handlerName,
        string commandTypeName,
        string resultType,
        string serviceName,
        string serviceTypeName,
        string methodName,
        bool isPublic)
    {
        var accessibility = isPublic ? "public" : "internal";
        var serviceParamName = GetParameterName(serviceName);

        // Class declaration with primary constructor
        _writer.WriteIndentedLine(
            "{0} sealed class {1}({2} {3})",
            accessibility,
            handlerName,
            serviceTypeName,
            serviceParamName);

        // Interface implementation
        _writer.IncreaseIndent();
        _writer.WriteIndentedLine(
            ": global::MediatR.IRequestHandler<{0}, {1}>",
            commandTypeName,
            resultType);
        _writer.DecreaseIndent();

        _writer.WriteIndentedLine("{");
        _writer.IncreaseIndent();

        // Handle method
        WriteHandleMethod(commandTypeName, resultType, serviceParamName, methodName);

        _writer.DecreaseIndent();
        _writer.WriteIndentedLine("}");
    }

    private void WriteHandleMethod(
        string commandTypeName,
        string resultType,
        string serviceParamName,
        string methodName)
    {
        _writer.WriteIndentedLine(
            "public async global::System.Threading.Tasks.Task<{0}> Handle(",
            resultType);

        using (_writer.IncreaseIndent())
        {
            _writer.WriteIndentedLine(
                "{0} request,",
                commandTypeName);
            _writer.WriteIndentedLine(
                "global::System.Threading.CancellationToken cancellationToken)");
        }

        _writer.WriteIndentedLine("{");

        using (_writer.IncreaseIndent())
        {
            _writer.WriteIndentedLine(
                "return await {0}.{1}(",
                serviceParamName,
                methodName);

            using (_writer.IncreaseIndent())
            {
                _writer.WriteIndentedLine("request,");
                _writer.WriteIndentedLine("cancellationToken).ConfigureAwait(false);");
            }
        }

        _writer.WriteIndentedLine("}");
    }

    public void WriteLine() => _writer.WriteLine();

    private static string GetParameterName(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "service";
        }

        // Remove 'I' prefix for interfaces
        if (name.StartsWith("I") && name.Length > 1 && char.IsUpper(name[1]))
        {
            name = name.Substring(1);
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    public override string ToString()
        => _sb.ToString();

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        PooledObjects.Return(_sb);
        _sb = null!;
        _writer = null!;
        _disposed = true;
    }
}
